# Car Price Prediction Using Machine Learning Algorithm

In [1]:
import pandas as pd
import numpy as np


# Data Collection and Processing

In [2]:
#Loading the dataset
car_data=pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
print(type(car_data))
car_data.head(10)

<class 'pandas.core.frame.DataFrame'>


name  year  selling_price  km_driven    fuel  \
0              Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2       Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3     Datsun RediGO T Option  2017         250000      46000  Petrol   
4      Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   
5       Maruti Alto LX BSIII  2007         140000     125000  Petrol   
6  Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol   
7   Tata Indigo Grand Petrol  2014         240000      60000  Petrol   
8   Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol   
9   Maruti Celerio Green VXI  2017         365000      78000     CNG   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  
5  Individual       Manual   First Owner  
6  Individual       Manual   First Owner  
7  Individual       Manual  Second Owner  
8  Individual       Manual   First Owner  
9  Individual       Manual   First Owner

In [3]:
#Checking Size of Dataframe
print(car_data.shape)
print("The Number of Rows in Dataset:- ",car_data.shape[0])
print("The Number of Colomns in Dataset:- ",car_data.shape[1])

(4340, 8)
The Number of Rows in Dataset:-  4340
The Number of Colomns in Dataset:-  8


In [4]:
#Checking Null values
car_data.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [5]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [6]:
car_data.describe()

year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000


# Checking Distribution of Categorical Data

In [7]:
#Checking Distribution of Categorical Data
#For Fuel
print("\n***Total Petrol engine Cars in our Dataset***")
car_data["fuel"].value_counts()


***Total Petrol engine Cars in our Dataset***


Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: fuel, dtype: int64

In [8]:
#Checking Distribution of Categorical Data
#For Seller Type
print("\n***Total Seller Types Of Cars in our Dataset are as Follow***")
car_data['seller_type'].value_counts()


***Total Seller Types Of Cars in our Dataset are as Follow***


Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [9]:
#Checking Distribution of Categorical Data
#For Gear Transmission
print("\n***Types Of Car Gear Transmission***")
car_data["transmission"].value_counts()


***Types Of Car Gear Transmission***


Manual       3892
Automatic     448
Name: transmission, dtype: int64

In [10]:
#Checking Distribution of Categorical Data
#For Car Owners
print("\n***Types Of Car Owners in Our Dataset***")
car_data["owner"].value_counts()


***Types Of Car Owners in Our Dataset***


First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

# Converting Text Data In Numeric Data

In [11]:
#Converting Text Data In Numeric Data
#For Fuel
car_data.replace({'fuel':{'Petrol':0,'Diesel':1,'CNG':2,'LPG':3,'Electric':4}},inplace=True)
print("\nAfter Replacing The Values, Count is ")
car_data["fuel"].value_counts()


After Replacing The Values, Count is 


1    2153
0    2123
2      40
3      23
4       1
Name: fuel, dtype: int64

In [12]:
#Converting Text Data In Numeric Data
#For Seller Type
car_data.replace({'seller_type':{'Individual':0,'Dealer':1,'Trustmark Dealer':2}},inplace=True)
print("\nAfter Replacing The Values, Count is ")
car_data['seller_type'].value_counts()


After Replacing The Values, Count is 


0    3244
1     994
2     102
Name: seller_type, dtype: int64

In [13]:
#Converting Text Data In Numeric Data
#For Gear Transmission
car_data.replace({'transmission':{'Manual':0,'Automatic':1}},inplace=True)
print("\nAfter Replacing The Values, Count is ")
car_data["transmission"].value_counts()


After Replacing The Values, Count is 


0    3892
1     448
Name: transmission, dtype: int64

In [14]:
#Converting Text Data In Numeric Data
#For Car Owners
car_data.replace({'owner':{'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth & Above Owner':3,'Test Drive Car':4}},inplace=True)
car_data["owner"].value_counts()

0    2832
1    1106
2     304
3      81
4      17
Name: owner, dtype: int64

In [15]:
car_data.head()

name  year  selling_price  km_driven  fuel  \
0             Maruti 800 AC  2007          60000      70000     0   
1  Maruti Wagon R LXI Minor  2007         135000      50000     0   
2      Hyundai Verna 1.6 SX  2012         600000     100000     1   
3    Datsun RediGO T Option  2017         250000      46000     0   
4     Honda Amaze VX i-DTEC  2014         450000     141000     1   

   seller_type  transmission  owner  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      1

By dropping Names from data our dataset contain only numeric values

In [16]:
car_data.drop("name",axis=1,inplace=True)
car_data.head(10)

year  selling_price  km_driven  fuel  seller_type  transmission  owner
0  2007          60000      70000     0            0             0      0
1  2007         135000      50000     0            0             0      0
2  2012         600000     100000     1            0             0      0
3  2017         250000      46000     0            0             0      0
4  2014         450000     141000     1            0             0      1
5  2007         140000     125000     0            0             0      0
6  2016         550000      25000     0            0             0      0
7  2014         240000      60000     0            0             0      1
8  2015         850000      25000     0            0             0      0
9  2017         365000      78000     2            0             0      0

In [17]:
car_data.shape

(4340, 7)

In [18]:
car_data.describe()

year  selling_price      km_driven         fuel  seller_type  \
count  4340.000000   4.340000e+03    4340.000000  4340.000000  4340.000000   
mean   2013.090783   5.041273e+05   66215.777419     0.531336     0.276037   
std       4.215344   5.785487e+05   46644.102194     0.549621     0.496892   
min    1992.000000   2.000000e+04       1.000000     0.000000     0.000000   
25%    2011.000000   2.087498e+05   35000.000000     0.000000     0.000000   
50%    2014.000000   3.500000e+05   60000.000000     1.000000     0.000000   
75%    2016.000000   6.000000e+05   90000.000000     1.000000     1.000000   
max    2020.000000   8.900000e+06  806599.000000     4.000000     2.000000   

       transmission       owner  
count   4340.000000  4340.00000  
mean       0.103226     0.46659  
std        0.304289     0.74033  
min        0.000000     0.00000  
25%        0.000000     0.00000  
50%        0.000000     0.00000  
75%        0.000000     1.00000  
max        1.000000     4.00000

In [19]:
X=car_data.drop(["selling_price"],axis=1)
Y=car_data["selling_price"]

In [20]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(X)
print("The Array of X scaled is:- ",x_scaled)

y_scaled=scaler.fit_transform([Y])
print("The Array of Y scaled is:- ",y_scaled)


The Array of X scaled is:-  [[-1.44507431  0.08113906 -0.9668441  -0.5555905  -0.33927557 -0.63031847]
 [-1.44507431 -0.3476891  -0.9668441  -0.5555905  -0.33927557 -0.63031847]
 [-0.2587948   0.7243813   0.85280178 -0.5555905  -0.33927557 -0.63031847]
 ...
 [-0.97056251  0.35987736 -0.9668441  -0.5555905  -0.33927557  0.7205863 ]
 [ 0.69022881  0.50996722  0.85280178 -0.5555905  -0.33927557 -0.63031847]
 [ 0.69022881 -0.56210318 -0.9668441  -0.5555905  -0.33927557 -0.63031847]]
The Array of Y scaled is:-  [[0. 0. 0. ... 0. 0. 0.]]


# Spitting The Dataset into Training & Testing

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X=car_data.drop(["selling_price"],axis=1)
Y=car_data["selling_price"]

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(x_scaled,Y,test_size=0.1)

In [24]:
X_train

array([[-0.97056251, -0.82726907, -0.9668441 , -0.5555905 , -0.33927557,
        -0.63031847],
       [ 0.4529729 ,  0.08113906,  0.85280178, -0.5555905 , -0.33927557,
         2.07149108],
       [-0.4960507 ,  0.7243813 , -0.9668441 , -0.5555905 , -0.33927557,
         0.7205863 ],
       ...,
       [ 0.92748471, -1.29111105, -0.9668441 , -0.5555905 , -0.33927557,
        -0.63031847],
       [ 0.92748471, -1.1944103 , -0.9668441 ,  1.45714971,  2.94745653,
        -0.63031847],
       [ 1.16474061, -0.80578478, -0.9668441 ,  1.45714971, -0.33927557,
        -0.63031847]])

In [25]:
print("X Train=",len(X_train))
print("X Test= ",len(X_test))
print()
print("Y Train=",len(Y_train))
print("Y Test= ",len(Y_test))

X Train= 3906
X Test=  434

Y Train= 3906
Y Test=  434


# Choosing Best Model For Prdicyion By Using GridSearchCV

In [26]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
''''model_params = {
    #For SVM
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    #For Random Forest
    'random_forest': {
        'model':RandomForestRegressor(),
        'params' : {
            'n_estimators': [1,10,35]
        }
    }
        
}'''

"'model_params = {\n    #For SVM\n    'svm': {\n        'model': SVC(gamma='auto'),\n        'params' : {\n            'C': [1,10,20],\n            'kernel': ['rbf','linear']\n        }  \n    },\n    #For Random Forest\n    'random_forest': {\n        'model':RandomForestRegressor(),\n        'params' : {\n            'n_estimators': [1,10,35]\n        }\n    }\n        \n}"

In [29]:
model_params = {
    #For Random Forest
    'random_forest': {
        'model':RandomForestRegressor(),
        'params' : {
            'n_estimators': [1,10,35]
        }
    }
        
}

In [30]:
scores = []

for model_name, mp in model_params.items():
    
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    
    clf.fit(X_train,Y_train)
    
    scores.append(
        {
            'model': model_name,
            'best_score': clf.best_score_,
            'best_params': clf.best_params_
        }
    )

In [31]:
data_frame = pd.DataFrame(scores,columns=['model','best_score','best_params'])
data_frame

model  best_score           best_params
0  random_forest    0.644225  {'n_estimators': 35}

By Using GridSearchCV we found that The Best algorithm to solve this problem is Random Forest Regressor. Similarly we can find which algorithm is best for the problem solving is by providing it as dictinary.

The only drawback of GridSearchCV is Computation time.

# Model Training

# 1. Random Forest Algorithm

In [32]:
rf_model=RandomForestRegressor(n_estimators=35)

#Training The Random Forest Model
rf_model.fit(X_train,Y_train)

rf_model.score(X_test,Y_test)

0.7287924866616846

In [33]:
from sklearn.model_selection import cross_val_score
rf_score=(cross_val_score(RandomForestRegressor(),X,Y,cv=10))
print(rf_score)

[0.54683388 0.79024728 0.7672229  0.56719117 0.5151516  0.86249266
 0.70958898 0.58246703 0.28543105 0.4789913 ]


In [34]:
#Calculating Score of individual model
print("Score of model before bagging:-",(np.average(rf_score)))


Score of model before bagging:- 0.6105617835222757


# Implementing Bagging To Improve The Score Of Model

In [35]:
from sklearn.ensemble import BaggingRegressor

bag_model=BaggingRegressor(
                            base_estimator=RandomForestRegressor(),
                            n_estimators=35,
                            max_samples=0.8,
                            oob_score=True,
                            random_state=1
                           )

In [36]:
bag_model.fit(X_train,Y_train)

BaggingRegressor(base_estimator=RandomForestRegressor(), max_samples=0.8,
                 n_estimators=35, oob_score=True, random_state=1)

In [37]:
#Score Before Cross Validation
print("Score of Bagging model before Cross Validation:- ",bag_model.score(X_test,Y_test))

Score of Bagging model before Cross Validation:-  0.7314778955352117


In [38]:
#Score of Out of bags elements
print("Score of Out of bags elements:- ",bag_model.oob_score_)


Score of Out of bags elements:-  0.6357387437622853


In [ ]:
#Applying Cross Validation
bag_model_score_with_cv=cross_val_score(bag_model,X,Y,cv=5)

In [ ]:
bag_model_score_with_cv

In [ ]:
#Score of Bagging model After Cross Validation
print("Score of Bagging model After Cross Validation:- ",bag_model_score_with_cv.mean())


# Overall Summary

In [ ]:
#Calculating Score of individual model
print("Score of model before bagging:-",(np.average(rf_score)))
print()

#Score After Bagging
print("Score of Model After Bagging :- ",bag_model.score(X_test,Y_test))
print()

#Score of Out of bags elements
print("Score of Out of bags elements:- ",bag_model.oob_score_)
print()

#Score Before Cross Validation
print("Score of Bagging model before Cross Validation:- ",bag_model.score(X_test,Y_test))
print()

#Score of Bagging model After Cross Validation
print("Score of Bagging model After Cross Validation:- ",bag_model_score_with_cv.mean())